services:
  app:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    depends_on:
      - db
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "120s", "npm", "start"]
    networks:
      - nginx_network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - nginx_network

volumes:
  mysql-data:
    driver: local

networks:
  nginx_network:
    external: true
