version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    depends_on:
      - db
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "120s", "npm", "start"]
    networks:
      - myapp-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootabid26
      MYSQL_DATABASE: vocabrodb
      MYSQL_USER: abid_vocabro
      MYSQL_PASSWORD: abid26
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - myapp-network

volumes:
  mysql-data:
    driver: local

networks:
  myapp-network:
    driver: bridge
